name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: addnab/docker-run-action@v3
        with:
          image: gcc:latest
          options: -v ${{ github.workspace }}:/usr/src/dln-api
          run: |
            cd /usr/src/dln-api/src/dln_api/libs
            gcc -shared -o x64.so -Wl,--whole-archive x64.a -Wl,--no-whole-archive x64.a
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install pypa/build
        run: python -m pip install build --user
      - name: Build package binary wheel/source tarball
        run: python -m build --sdist --wheel
      - uses: actions/upload-artifact@v4
        with:
          name: pypi-package
          path: ./dist
  publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-22.04
    needs: [ build ]
    environment:
      name: pypi
      url: https://pypi.org/p/dln-api
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: pypi-package
          path: ./dist
      - name: Publish package on PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
